# Варіант 10

# Завдання 1

In [1]:
import numpy as np

In [2]:
matrix = np.random.randint(1, 11, size=(3, 4))

In [3]:
vector = np.random.randint(1, 11, size=(4, 1))

In [4]:
result = np.dot(matrix, vector)


In [5]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[ 6  6  1 10]
 [ 9  7  3  4]
 [10  9  5 10]]

Вектор 4x1:
[[ 4]
 [10]
 [ 7]
 [ 3]]

Добуток матриці на вектор:
[[121]
 [139]
 [195]]


# Завдання 2

In [6]:
matrix = np.random.randint(1, 11, size=(3, 4))

In [7]:
vector = np.random.randint(1, 11, size=(4, 1))

In [8]:
mean_value = np.mean(matrix)

In [9]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nСереднє значення елементів матриці:")
print(mean_value)

Матриця 3x4:
[[ 2 10  8  2]
 [ 6  1  8  7]
 [ 2  4 10  5]]

Вектор 4x1:
[[ 2]
 [ 8]
 [10]
 [ 5]]

Середнє значення елементів матриці:
5.416666666666667


# Завдання 3

In [10]:
result = np.dot(matrix, vector)

In [11]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[ 2 10  8  2]
 [ 6  1  8  7]
 [ 2  4 10  5]]

Вектор 4x1:
[[ 2]
 [ 8]
 [10]
 [ 5]]

Добуток матриці на вектор:
[[174]
 [135]
 [161]]


#  Завдання 4

In [14]:
matrix = np.random.randint(1, 11, size=(3, 4))

In [15]:
vector = np.random.rand(4, 1)

In [16]:
result = np.dot(matrix, vector)

In [17]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[ 2 10 10  5]
 [ 6  4  8  7]
 [ 6  1  6  7]]

Вектор 4x1:
[[0.18901329]
 [0.72387731]
 [0.74229659]
 [0.67071271]]

Добуток матриці на вектор:
[[18.39332917]
 [14.66295073]
 [11.00672562]]


# Завдання 5

In [18]:
matrix = np.random.rand(3, 4)

In [19]:
vector = np.random.randint(1, 11, size=(4, 1))

In [20]:
result = np.dot(matrix, vector)

In [21]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.95420632 0.13950819 0.80479648 0.07395729]
 [0.72570422 0.82445713 0.7156506  0.08974343]
 [0.69334114 0.9257872  0.75417253 0.8519383 ]]

Вектор 4x1:
[[2]
 [9]
 [2]
 [7]]

Добуток матриці на вектор:
[[ 5.29128039]
 [10.93102777]
 [17.19068022]]


# Завдання 6

In [22]:
matrix = np.random.rand(3, 4)

In [23]:
vector = np.random.rand(4, 1)

In [24]:
result = np.dot(matrix, vector)

In [25]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.72935501 0.07461995 0.95304977 0.84585685]
 [0.15211785 0.54384543 0.51522852 0.54584938]
 [0.40314812 0.92341688 0.31551324 0.93214547]]

Вектор 4x1:
[[0.03337275]
 [0.95083716]
 [0.07771336]
 [0.3660105 ]]

Добуток матриці на вектор:
[[0.47894918]
 [0.76201178]
 [1.25716787]]


# Завдання 7

In [26]:
matrix = np.random.randint(-5, 6, size=(3, 4))

In [27]:
vector = np.random.randint(1, 11, size=(4, 1))

In [28]:
result = np.dot(matrix, vector)

In [29]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[ 4 -1  1  4]
 [ 0 -3  0 -2]
 [-2 -1 -1  4]]

Вектор 4x1:
[[7]
 [3]
 [4]
 [9]]

Добуток матриці на вектор:
[[ 65]
 [-27]
 [ 15]]


# Завдання 8

In [30]:
matrix = np.random.randint(1, 11, size=(3, 4))

In [31]:
vector = np.random.rand(4, 1)

In [32]:
result = np.dot(matrix, vector)


In [33]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[ 8  1  7 10]
 [ 7  1  5  8]
 [ 5  6  2  1]]

Вектор 4x1:
[[0.56444862]
 [0.99266533]
 [0.95967433]
 [0.97502069]]

Добуток матриці на вектор:
[[21.97618154]
 [17.54234287]
 [11.67260443]]


# Завдання 9

In [34]:
matrix = np.random.rand(3, 4)

In [35]:
vector = np.random.randint(1, 11, size=(4, 1))

In [36]:
result = np.dot(matrix, vector)

In [37]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.63049074 0.4750481  0.78339013 0.55455744]
 [0.12348961 0.34526408 0.38387229 0.59036914]
 [0.8504996  0.83774108 0.07286681 0.39260713]]

Вектор 4x1:
[[10]
 [ 4]
 [ 2]
 [10]]

Добуток матриці на вектор:
[[15.31745444]
 [ 9.28738839]
 [15.92776523]]


# Завдання 10

In [40]:
matrix = np.random.randint(-5, 6, size=(3, 4))

In [41]:
vector = np.random.rand(4, 1)

In [42]:
result = np.dot(matrix, vector)

In [43]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[ 5  5 -1  0]
 [ 0  0  1  0]
 [ 5 -5 -4  2]]

Вектор 4x1:
[[0.24635105]
 [0.85414131]
 [0.04850441]
 [0.28211518]]

Добуток матриці на вектор:
[[ 5.45395739]
 [ 0.04850441]
 [-2.66873857]]


# Завдання 11

In [44]:
matrix = np.random.rand(3, 4)

In [45]:
vector = np.random.rand(4, 1)

In [46]:
result = np.dot(matrix, vector)


In [47]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.63034183 0.46597292 0.71532942 0.66415955]
 [0.526616   0.79862528 0.6506972  0.29746937]
 [0.78689277 0.30005725 0.88972386 0.05096048]]

Вектор 4x1:
[[0.11563493]
 [0.41806307]
 [0.94507335]
 [0.47156702]]

Добуток матриці на вектор:
[[1.25693012]
 [1.15000427]
 [1.08132074]]


# Завдання 12

In [48]:
matrix = 2 * np.random.rand(3, 4) - 1
vector = np.random.randint(-3, 4, size=(4, 1))
result = np.dot(matrix, vector)

In [49]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[-0.54798056 -0.51134331 -0.77720193  0.79268667]
 [-0.69926711 -0.89891393 -0.95060368 -0.10522252]
 [-0.77778247 -0.58988415  0.34348217 -0.53166449]]

Вектор 4x1:
[[-2]
 [-3]
 [ 0]
 [ 2]]

Добуток матриці на вектор:
[[4.21536439]
 [3.88483098]
 [2.2618884 ]]


# Завдання 13

In [50]:
matrix = np.random.randint(1, 11, size=(3, 4))

In [51]:
vector = np.random.rand(4, 1)

In [52]:
result = np.dot(matrix, vector)

In [53]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[8 9 1 5]
 [2 8 9 9]
 [5 3 3 9]]

Вектор 4x1:
[[0.38941164]
 [0.91517538]
 [0.19127138]
 [0.00452156]]

Добуток матриці на вектор:
[[11.5657507 ]
 [ 9.86236274]
 [ 5.30709251]]


# Завдання 14

In [54]:
matrix = np.random.rand(3, 4)

In [55]:
vector = np.random.rand(4, 1)

In [56]:
result = np.dot(matrix, vector)

In [57]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.33252822 0.28515792 0.64925996 0.52954205]
 [0.82189688 0.7317689  0.55823957 0.06837241]
 [0.8882437  0.8357136  0.43921516 0.06779289]]

Вектор 4x1:
[[0.51779521]
 [0.02440284]
 [0.78838736]
 [0.79098962]]

Добуток матриці на вектор:
[[1.10987079]
 [0.93762239]
 [0.88021727]]


# Завдання 15 

In [58]:
matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, size=(4, 1))
result = np.dot(matrix, vector)

In [59]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.73064187 0.79464138 0.54118645 0.13496697]
 [0.7673979  0.14116656 0.46026995 0.86384056]
 [0.3135188  0.06526847 0.23708287 0.38256736]]

Вектор 4x1:
[[10]
 [ 9]
 [ 3]
 [ 9]]

Добуток матриці на вектор:
[[17.29645313]
 [18.09985293]
 [ 7.87695909]]


# Завдання 16

In [60]:
matrix = np.random.rand(3, 4)
vector = np.random.rand(4, 1)
result = np.dot(matrix, vector)

In [61]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.02338748 0.49079385 0.63553499 0.2752914 ]
 [0.95456372 0.48662783 0.8161236  0.29987915]
 [0.23063311 0.38709257 0.39947076 0.49978315]]

Вектор 4x1:
[[0.96752015]
 [0.95498544]
 [0.19616316]
 [0.46751627]]

Добуток матриці на вектор:
[[0.74470061]
 [1.68857389]
 [0.90482815]]


# Завдання 17

In [62]:
matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, size=(4, 1))
result = np.dot(matrix, vector)

In [63]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.70627244 0.18442942 0.16847078 0.37914932]
 [0.62365465 0.32810766 0.34849666 0.72487851]
 [0.53184499 0.65306444 0.41874892 0.93396515]]

Вектор 4x1:
[[1]
 [4]
 [5]
 [5]]

Добуток матриці на вектор:
[[4.18209062]
 [7.30296118]
 [9.90767312]]


# Завдання 18

In [64]:
matrix = np.random.rand(3, 4)
vector = np.random.rand(4, 1)
result = np.dot(matrix, vector)

In [65]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.23387556 0.11596459 0.81532585 0.87920918]
 [0.59798016 0.99187023 0.45296935 0.31695762]
 [0.97175352 0.6795806  0.98291979 0.923011  ]]

Вектор 4x1:
[[0.79269642]
 [0.36458491]
 [0.73408447]
 [0.26782423]]

Добуток матриці на вектор:
[[1.06166282]
 [1.25304435]
 [1.98682122]]


# Завдання 19

In [68]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.rand(4, 1)
result = np.dot(matrix, vector)

In [69]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[1 5 9 2]
 [7 6 1 2]
 [1 9 2 5]]

Вектор 4x1:
[[0.78539367]
 [0.81499554]
 [0.38960112]
 [0.2659966 ]]

Добуток матриці на вектор:
[[ 8.89877469]
 [11.30932329]
 [10.22953881]]


# Завдання 20

In [66]:
matrix = np.random.rand(3, 4)
vector = np.random.rand(4, 1)
result = np.dot(matrix, vector)

In [67]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.18731634 0.07109012 0.64088552 0.63542631]
 [0.56886749 0.33596063 0.91413697 0.17315137]
 [0.09346246 0.15667044 0.56512071 0.72666455]]

Вектор 4x1:
[[0.54006304]
 [0.06930889]
 [0.02067253]
 [0.46868039]]

Добуток матриці на вектор:
[[0.41715038]
 [0.43055954]
 [0.41359017]]


# Завдання 21

In [70]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.rand(4, 1)
result = np.dot(matrix, vector)

In [71]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[ 7  1 10  8]
 [ 2  9  2  4]
 [10  5  8  2]]

Вектор 4x1:
[[0.51838514]
 [0.44191584]
 [0.51406158]
 [0.14436297]]

Добуток матриці на вектор:
[[10.36613139]
 [ 6.61958787]
 [11.79464918]]


# Завдання 22

In [72]:
matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, size=(4, 1))
result = np.dot(matrix, vector)

In [73]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.88698354 0.57930768 0.92399923 0.19933368]
 [0.63443862 0.73266478 0.67298804 0.25996321]
 [0.1520036  0.98779344 0.03426305 0.30268604]]

Вектор 4x1:
[[1]
 [7]
 [7]
 [6]]

Добуток матриці на вектор:
[[12.60613397]
 [12.03378757]
 [ 9.12251528]]


# Завдання 23

In [74]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=(4, 1))
result = np.dot(matrix, vector)

In [75]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[ 1  7  7 10]
 [ 3 10  1  4]
 [10  5  1  3]]

Вектор 4x1:
[[2]
 [8]
 [3]
 [9]]

Добуток матриці на вектор:
[[169]
 [125]
 [ 90]]


# Завдання 24

In [76]:
matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, size=(4, 1))
result = np.dot(matrix, vector)

In [77]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)


Матриця 3x4:
[[0.58958422 0.16388301 0.61362788 0.09420417]
 [0.1223686  0.28734761 0.40943063 0.99066914]
 [0.16769994 0.06792083 0.25427314 0.64977972]]

Вектор 4x1:
[[ 1]
 [10]
 [ 7]
 [ 6]]

Добуток матриці на вектор:
[[ 7.08903457]
 [11.80587392]
 [ 6.52549852]]


# Завдання 25

In [78]:
matrix = np.random.rand(3, 4)
vector = np.random.rand(4, 1)
result = np.dot(matrix, vector)

In [79]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.1479274  0.29267684 0.67472009 0.84597977]
 [0.093527   0.00703822 0.04163924 0.28592675]
 [0.63399245 0.6641633  0.0348378  0.52365132]]

Вектор 4x1:
[[0.2636261 ]
 [0.22017245]
 [0.23519126]
 [0.91075667]]

Добуток матриці на вектор:
[[1.03260689]
 [0.29640865]
 [0.7984799 ]]


# Завдання 26

In [80]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.rand(4, 1)
result = np.dot(matrix, vector)

In [81]:
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[ 4 10 10  9]
 [ 1  3  4  5]
 [ 9  8 10 10]]

Вектор 4x1:
[[0.04416804]
 [0.38091287]
 [0.8790559 ]
 [0.77087328]]

Добуток матриці на вектор:
[[19.71421942]
 [ 8.55749667]
 [19.94410719]]


# Завдання 27

In [82]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=(4, 1))
result = np.dot(matrix, vector)

print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[ 9  5 10  3]
 [10 10  5  9]
 [ 5  3  4  9]]

Вектор 4x1:
[[5]
 [2]
 [3]
 [3]]

Добуток матриці на вектор:
[[ 94]
 [112]
 [ 70]]


# Завдання 28

In [83]:
matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, size=(4, 1))
result = np.dot(matrix, vector)

print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.42935508 0.99652805 0.3547043  0.80785537]
 [0.60441141 0.02825651 0.33731526 0.95056277]
 [0.01854186 0.88914074 0.64042507 0.13703587]]

Вектор 4x1:
[[ 7]
 [ 5]
 [10]
 [ 8]]

Добуток матриці на вектор:
[[17.99801173]
 [15.34981718]
 [12.07603438]]


# Завдання 29

In [84]:
matrix = np.random.rand(3, 4)
vector = np.random.rand(4, 1)
result = np.dot(matrix, vector)

print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.44300705 0.90402714 0.76246719 0.67654615]
 [0.33721078 0.31934835 0.46357913 0.85829898]
 [0.46685125 0.55505031 0.47875144 0.19847508]]

Вектор 4x1:
[[0.62712084]
 [0.70361624]
 [0.76133367]
 [0.41870029]]

Добуток матриці на вектор:
[[1.77766914]
 [1.14847903]
 [1.13090572]]


# Завдання 30

In [85]:
matrix = np.random.rand(3, 4)
vector = np.random.rand(4, 1)
result = np.dot(matrix, vector)

print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.81610886 0.97916426 0.21991567 0.49182309]
 [0.35801037 0.38624158 0.68999853 0.06874366]
 [0.17068605 0.83930987 0.02945367 0.72975412]]

Вектор 4x1:
[[0.71731067]
 [0.22983654]
 [0.33207093]
 [0.12085699]]

Добуток матриці на вектор:
[[0.94291918]
 [0.5830137 ]
 [0.41331559]]


Висновок 
Для генерації матриць і векторів з випадковими значеннями використовуються функції з бібліотеки NumPy, 
такі як np.random.randint() для цілих чисел і np.random.rand() для дійсних чисел.
Операція множення матриці на вектор обчислюється за допомогою функції np.dot(), яка реалізує стандартне матричне множення.